name: issues

on:
  issues:
    types: [opened, reopened, closed]

jobs:
  irc:
    runs-on: ubuntu-latest
    steps:
      - name: "notify: new"
        uses: rectalogic/notify-irc@v1
        if: github.event.issue.state == 'open'
        with:
          server: chat.freenode.net
          nickname: cala-issues
          channel: "#calamares"
          message: "OPENED ${{ github.event.issue.html_url }} by ${{ github.actor }} ${{ github.event.issue.title }}"
      - name: "notify: closed"
        uses: rectalogic/notify-irc@v1
        if: github.event.issue.state != 'open'
        with:
          server: chat.freenode.net
          nickname: cala-issues
          channel: "#calamares"
          message: "CLOSED ${{ github.event.issue.html_url }} by ${{ github.actor }} ${{ github.event.issue.title }}"
