name: 'Notify on Push'
description: 'Notify Matrix room'

inputs:
  room:
    description: 'Matrix Room ID'
    required: true
  token:
    description: 'Matrix Token'
    required: true
  message:
    description: 'Message to send'
    required: true

runs:
  using: "composite"
  steps:
    - run: echo "Before"
      shell: bash
    - run: echo "$INPUT_MESSAGE"
      shell: bash
    - run: echo "After"
      shell: bash
